/**
 * AssetProvenanceService - Generates credits.json manifest for transparency
 * 
 * Creates a sidecar file documenting:
 * - Music source and licensing
 * - Image sources (AI-generated vs scraped)
 * - Voice synthesis provider
 * - Compliance scan results
 */

import fs from 'fs/promises';
import path from 'path';

/**
 * Music credit entry
 */
export interface MusicCredit {
    trackName: string;
    source: 'catalog' | 'ai_generated' | 'stock';
    catalogId?: string;
    license: string;
    attribution?: string;
}

/**
 * Image credit entry
 */
export interface ImageCredit {
    sceneIndex: number;
    source: 'flux' | 'scraped' | 'stock' | 'user_provided';
    prompt?: string;
    originalUrl?: string;
    synthetic: boolean;
    license: string;
}

/**
 * Voice credit entry
 */
export interface VoiceCredit {
    provider: 'fish_audio' | 'xtts' | 'elevenlabs';
    voiceId: string;
    synthetic: boolean;
    language: string;
    clonedFrom?: 'user_voice' | 'stock_voice';
}

/**
 * Full credits manifest
 */
export interface CreditsManifest {
    /** Version of the manifest format */
    version: '1.0.0';
    /** Job ID this manifest belongs to */
    jobId: string;
    /** Video ID if different from job ID */
    videoId?: string;
    /** When the video was generated */
    generatedAt: string;
    /** Music credits */
    music: MusicCredit;
    /** Image credits per scene */
    images: ImageCredit[];
    /** Voice credit */
    voice: VoiceCredit;
    /** Compliance information */
    compliance: {
        scanned: boolean;
        auditId?: string;
        profileUsed?: string;
        score?: number;
        approved?: boolean;
    };
    /** Data retention policy */
    dataRetention: {
        purgeDueAt: string;
        retentionHours: number;
    };
    /** Impressum / Legal footer */
    legal: {
        generator: string;
        contactEmail?: string;
        impressumUrl?: string;
    };
}

/**
 * Generates a credits.json manifest from job data
 */
export function generateCreditsManifest(
    jobId: string,
    options: {
        music: MusicCredit;
        images: ImageCredit[];
        voice: VoiceCredit;
        complianceAuditId?: string;
        complianceProfile?: string;
        complianceScore?: number;
        complianceApproved?: boolean;
        retentionHours?: number;
        contactEmail?: string;
        impressumUrl?: string;
    }
): CreditsManifest {
    const now = new Date();
    const retentionHours = options.retentionHours ?? 24;
    const purgeDue = new Date(now.getTime() + retentionHours * 60 * 60 * 1000);

    return {
        version: '1.0.0',
        jobId,
        generatedAt: now.toISOString(),
        music: options.music,
        images: options.images,
        voice: options.voice,
        compliance: {
            scanned: !!options.complianceAuditId,
            auditId: options.complianceAuditId,
            profileUsed: options.complianceProfile,
            score: options.complianceScore,
            approved: options.complianceApproved,
        },
        dataRetention: {
            purgeDueAt: purgeDue.toISOString(),
            retentionHours,
        },
        legal: {
            generator: 'InstagramReelPoster v1.0',
            contactEmail: options.contactEmail,
            impressumUrl: options.impressumUrl,
        },
    };
}

/**
 * Writes credits manifest to disk alongside video
 */
export async function writeCreditsManifest(
    manifest: CreditsManifest,
    outputDir: string
): Promise<string> {
    await fs.mkdir(outputDir, { recursive: true });
    const filename = `credits_${manifest.jobId}.json`;
    const filepath = path.join(outputDir, filename);

    await fs.writeFile(filepath, JSON.stringify(manifest, null, 2), 'utf-8');
    console.log(`[AssetProvenance] Credits manifest saved: ${filename}`);

    return filepath;
}

/**
 * Creates a default music credit for AI-generated music
 */
export function createAiMusicCredit(provider: string = 'suno'): MusicCredit {
    return {
        trackName: 'AI Generated',
        source: 'ai_generated',
        license: 'Generated for single-use',
        attribution: `Generated by ${provider}`,
    };
}

/**
 * Creates a default music credit for catalog music
 */
export function createCatalogMusicCredit(
    trackName: string,
    catalogId: string
): MusicCredit {
    return {
        trackName,
        source: 'catalog',
        catalogId,
        license: 'Royalty-free (catalog)',
    };
}

/**
 * Creates an image credit for Flux-generated images
 */
export function createFluxImageCredit(
    sceneIndex: number,
    prompt: string
): ImageCredit {
    return {
        sceneIndex,
        source: 'flux',
        prompt,
        synthetic: true,
        license: 'AI-generated for single-use',
    };
}

/**
 * Creates an image credit for scraped website images
 */
export function createScrapedImageCredit(
    sceneIndex: number,
    originalUrl: string
): ImageCredit {
    return {
        sceneIndex,
        source: 'scraped',
        originalUrl,
        synthetic: false,
        license: 'Source website - verify usage rights',
    };
}
