/**
 * Track represents a music track, either from a catalog or AI-generated.
 */
export interface Track {
    /** Unique identifier for the track */
    id: string;
    /** Optional title of the track */
    title?: string;
    /** Tags describing the track's mood, genre, instruments */
    tags: string[];
    /** Duration of the track in seconds */
    durationSeconds: number;
    /** URL to the audio file (MP3) */
    audioUrl: string;
    /** True if this track was generated by AI (VideoGen/Suno) */
    isAIGenerated?: boolean;
}

/**
 * Creates a new Track with validated properties.
 */
export function createTrack(params: {
    id: string;
    title?: string;
    tags: string[];
    durationSeconds: number;
    audioUrl: string;
    isAIGenerated?: boolean;
}): Track {
    if (!params.id.trim()) {
        throw new Error('Track id cannot be empty');
    }
    if (params.durationSeconds <= 0) {
        throw new Error('Track durationSeconds must be positive');
    }
    if (!params.audioUrl.trim()) {
        throw new Error('Track audioUrl cannot be empty');
    }

    return {
        id: params.id.trim(),
        title: params.title?.trim(),
        tags: params.tags.map(tag => tag.trim().toLowerCase()),
        durationSeconds: params.durationSeconds,
        audioUrl: params.audioUrl.trim(),
        isAIGenerated: params.isAIGenerated ?? false,
    };
}

/**
 * Checks if a track matches any of the given tags.
 */
export function trackMatchesTags(track: Track, requiredTags: string[]): boolean {
    const normalizedRequired = requiredTags.map(t => t.trim().toLowerCase());
    return normalizedRequired.some(tag => track.tags.includes(tag));
}

/**
 * Checks if a track's duration is within an acceptable range.
 */
export function trackFitsDuration(
    track: Track,
    targetDuration: number,
    tolerancePercent: number = 0.3
): boolean {
    const minDuration = targetDuration * (1 - tolerancePercent);
    const maxDuration = targetDuration * (1 + tolerancePercent);
    return track.durationSeconds >= minDuration && track.durationSeconds <= maxDuration;
}
